### ISSUE TITLE
Download a list (or text file) of all available courses on codecourse.com

### ISSUE THREAD

**Issue by connecteev** [muhamed-didovic/ccdown#6]
Option to download a list (or text file) of all available courses on codecourse.com

Use-case: 
Getting this list periodically will allow me to see which courses have been added or changed.

**Comment by muhamed-didovic** [comment]
Hey @connecteev, you are pretty active :), anyways thank you for sharing your feedback and ideas as well in order to improve the downloader

There is already a file with all courses called search-courses.json here https://github.com/muhamed-didovic/ccdown/blob/main/json/search-courses.json

This list of all courses will be shown if you choose the option not to download all courses, basically, you can filter out courses that you want

**Comment by connecteev** [comment]
Thanks @muhamed-didovic! I have seen this file and tried that option - works great for filtering / downloading a specific course. I have also tried to edit the file and feed it to ccdown (basically what I tried here: #3), though that didn't work - as you said, it wasn't the intended purpose at the time.

How is this static list / json file kept updated as new courses get downloaded? It would be nice to allow the user to get an exhaustive list of all courses, update it and feed it back to ccdown. See step 1 here:
https://github.com/muhamed-didovic/ccdown/issues/3#issuecomment-1602608106

**Comment by muhamed-didovic** [comment]
file is updated either by me or another way is if user selects to download one course and then he gets this question: 'Do you want to search for a courses from a local file (which is faster)' if he chooses no, I hit the API and get all courses and update the file

**Comment by connecteev** [comment]
Hey there @muhamed-didovic just checking in - is there a way to do this?
